---
title: "02-Table1"
author: "Ronil V. Chandra"
date: "9/08/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

###Load packages

```{r load packages, echo = FALSE, include = FALSE}

library(tidyverse)
library(kableExtra)
```

#### Load required data

A single excel data file is loaded to carry out all data table creation, with all steps documented below to ensure reproducibility of research.

```{r load data, echo = FALSE, include = FALSE}

maindata <- read_csv("data/final_data_SR_MA_02.csv")
```


### Analyse total cohort of all aneurysms 10 mm and less 

```{r select 10 mm and less}

sizedata10 <- filter(maindata, size == 10) 

```


```{r create data for table}

tabledata <- sizedata10 %>%
  mutate(prop_multi = multi_tot / num_tot,
         num_multi = prop_multi * num + num,
         num_multi_temp = coalesce(num_anr, num_multi),
         total_size_temp = coalesce(num_anr, num),
         total_size_temp_2 = coalesce(num_multi_temp, total_size_temp),
         total_size = round(total_size_temp_2, 0),
         psah_size_temp = psah * prop_multi + psah,
         prop_psah = psah_tot / num_tot,
         num_anr_psah = prop_psah * total_size,
         size_psah_temp = coalesce(psah_size_temp, num_anr_psah),
         psah_size = round(size_psah_temp, 0),
         ) %>%
  mutate(fu_mean_year = fu_mean_tot / 12) %>%
  mutate(fu_med_year = fu_med_tot / 12) %>%
  mutate(fu = coalesce(fu_mean_tot,fu_med_tot) / 12) %>%
  mutate(age = coalesce(age_mean, age_med)) %>%
  mutate(age_cat = case_when (
    age == 65 | age < 65 ~ "≤65-years",
    age > 65 ~ ">65-years"
    )) %>%
  unite(auth_year, c(auth, pub), sep = " ", remove = FALSE) %>%
  mutate(pop = fct_collapse(sizedata10$country, 
                            "Japanese" = "Japan", 
                            "Non-Japanese" = c("International", 
                                               "United States", 
                                               "Switzerland", 
                                               "Australia", 
                                               "Korea", 
                                               "Poland", 
                                               "China", 
                                               "Germany", 
                                               "United Kingdom", 
                                               "Finland")) 
         ) 

```

```{r select columns for table}

tabledata.final <- tabledata %>%
  select(auth_year, 
         start, 
         end, 
         country, 
         type, 
         age_mean, 
         age_med, 
         num_tot, 
         num_anr_tot, 
         psah_tot, 
         multi_tot, 
         fu_mean_year, 
         fu_med_year, 
         num, 
         num_anr, 
         rupt, 
         rupt_psah, 
         nos_total) %>%
  arrange(desc(nos_total), desc(num))

```



## Table 1 Baseline Characteristics 


```{r, Table 1, Baseline Characteristics, results = 'asis'}

tabledata.final %>%
  knitr::kable(
    caption = "Table 1: Baseline Study Characteristics",
    col.names = c("Study", 
                  "Study-year start", 
                  "Study-year end", 
                  "Source population", 
                  "Study type", 
                  "Mean age", 
                  "Median age", 
                  "No. of total patients in follow-up", 
                  "No. of total aneurysms in follow up", 
                  "No. of total patients with prior SAH", 
                  "No. of total patients with multiple aneurysms", 
                  "Mean follow-up (Years)", 
                  "Median follow-up (Years)", 
                  "No. of patients with ≤10mm aneurysms", 
                  "No. of ≤10mm aneurysms", 
                  "No. of patients with rupture", 
                  "No. of patients with prior SAH and rupture", 
                  "NOS quality score"),
    align = c("l", "c", "c", "c", "c","c", "c", "c", "c", "c", "c", "c", "c", "c", "c", "c"),
    longtable=TRUE,
    digits = 1) %>%
  kableExtra::kable_styling(bootstrap = "striped", 
                            full_width = FALSE,
                            font_size = 10,
                            ) %>%
  footnote(
    general_title = "Footnote:",
    general = "SAH = Subrachnoid haemorrhage",
    threeparttable=TRUE,
    )


```


